---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  chart:
    spec:
      chart: nginx
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: mycharts
        namespace: flux-system
  interval: 1m0s

